backend:
  name: git-gateway
  branch: main

media_folder: "site/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - file: "site/portfolio.json"
        label: "Galerie photos"
        name: "gallery"
        fields:
          - label: "Événementiel"
            name: "evenementiel"
            widget: "list"
            label_singular: "Photo"
            summary: "{{caption}}"
            min: 0
            max: 5
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Légende (optionnelle)", name: "caption", widget: "string", required: false}
          - label: "Portrait"
            name: "portrait"
            widget: "list"
            label_singular: "Photo"
            summary: "{{caption}}"
            min: 0
            max: 5
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Légende (optionnelle)", name: "caption", widget: "string", required: false}
          - label: "Studio"
            name: "studio"
            widget: "list"
            label_singular: "Photo"
            summary: "{{caption}}"
            min: 0
            max: 5
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Légende (optionnelle)", name: "caption", widget: "string", required: false}
          - label: "Photoshoot"
            name: "photoshoot"
            widget: "list"
            label_singular: "Photo"
            summary: "{{caption}}"
            min: 0
            max: 5
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Légende (optionnelle)", name: "caption", widget: "string", required: false}
